- name: copy shipping service local to remote
  ansible.builtin.copy:
    src: shipping.service
    dest: /etc/systemd/system/shipping.service

- name: Use role in loop
  ansible.builtin.include_role:
    name: common
    tasks_from: "{{ role_items }}"
  loop:
    - node.yaml
    - main.yaml
    - backend_script.yaml
  loop_control:
    loop_var: role_items
