- name: copy user local to remote
  ansible.builtin.copy:
    src: user.service
    dest: /etc/systemd/system/user.service

- name: import node
  ansible.builtin.include_role:
    name: common
    tasks_from: node.yaml

- name: import npm
  ansible.builtin.include_role:
    name: common
    tasks_from: npm.yaml


- name: import backend script
  ansible.builtin.include_role:
    name: common
    tasks_from: backend_script.yaml