- name: copy payment service local to remote
  ansible.builtin.copy:
    src: payment.service
    dest: /etc/systemd/system/payment.service

- name: Install python3 package
  ansible.builtin.dnf:
    name:
      - python3
      - gcc
      - python3-devel
    state: present

- name: import node
  ansible.builtin.include_role:
    name: common
    tasks_from: node.yaml

- name: Install requirements
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    executable: pip3

- name: import node
  ansible.builtin.include_role:
    name: common
    tasks_from: backend_script.yaml