- name: copy catalogue service local to remote
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: copy mongo repo local to remote
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install nodejs package
  ansible.builtin.dnf:
    name: '@nodejs:20'
    state: present

- name: Create a user
  ansible.builtin.user:
    name: roboshop

- name: Remove app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: make a directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download catalogue
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
    dest: /tmp/catalogue.zip

- name: Extract catalogue
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app
    remote_src: yes

- name: Install npm
  community.general.npm:
    name: npm
    path: /app

- name: Install mongodb-mongosh
  ansible.builtin.dnf:
    name: 'mongodb-mongosh'
    state: present

- name: Load schema
  ansible.builtin.shell: mongosh --host mongodb-dev.pdevops78.online </app/db/master-data.js

- name: start catalogue service
  ansible.builtin.systemd_service:
    name: catalogue
    daemon-reload: true
    state: started
    enabled: true
