- name: copy service local to remote
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: import common code
  ansible.builtin.include_role:
    name: common


- name: Use role in loop
  ansible.builtin.include_role:
    name: common
    tasks_from: "{{ role_items }}"
  loop:
    - npm.yaml
    - mongo.yaml
    - backend_script.yaml
  loop_control:
    loop_var: role_items