- name: copy catalogue service local to remote
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: import role
  ansible.builtin.import_role:
    name: common