- name: copy catalogue service local to remote
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: import node
  ansible.builtin.include_role:
    name: common
    tasks_from: node.yaml

- name: import node
  ansible.builtin.include_role:
    name: common
    tasks_from: mongo.yaml

- name: import backend script
  ansible.builtin.include_role:
    name: common
    tasks_from: backend_script.yaml


