- name: copy service local to remote file
  ansible.builtin.import_tasks:
    file: service

- name: copy service local to remote file
  ansible.builtin.import_tasks:
    file: mongo


- name: import node
  ansible.builtin.import_tasks:
    file: node


- name: import backend script
  ansible.builtin.import_tasks:
    file: backend_script



