- name: copy mongo repo local to remote
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb-mongosh
  ansible.builtin.dnf:
    name: 'mongodb-mongosh'
    state: present

- name: Load schema
  ansible.builtin.shell: mongosh --host mongodb-dev.pdevops78.online </app/db/master-data.js