- name: copy mongo repo local to remote
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb-mongosh
  ansible.builtin.dnf:
    name: 'mongodb-mongosh'
    state: present

- name: import node
  ansible.builtin.import_tasks:
    file: node.yaml

- name: Load schema
  ansible.builtin.shell: mongosh --host 172.31.25.212 </app/db/master-data.js