- name: Install nodejs package
  ansible.builtin.dnf:
    name: '@nodejs:20'
    state: present

- name: Create a user
  ansible.builtin.user:
    name: roboshop

- name: Remove app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: make a directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download catalogue
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
    dest: /tmp/catalogue.zip

- name: Extract catalogue
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app
    remote_src: yes

- name: Install npm
  community.general.npm:
    name: npm
    path: /app


