- name: copy cart service local to remote
  ansible.builtin.copy:
    src: {{component}}.service
    dest: /etc/systemd/system/{{component}}.service

#
#- name: import node
#  ansible.builtin.include_role:
#    name: common
#    tasks_from: node.yaml


- name: Use role in loop
  ansible.builtin.include_role:
    name: common
    tasks_from: "{{ role_items }}"
  loop:
    - node.yaml
    - npm.yaml
    - backend_script.yaml
  loop_control:
    loop_var: role_items